# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/nbdev-test',
                'doc_host': 'https://Baldr27.github.io',
                'git_url': 'https://github.com/Baldr27/nbdev-test',
                'lib_path': 'nbdev_test'},
  'syms': { 'nbdev_test.asociacion': { 'nbdev_test.asociacion.say_hello': ( 'intro_reglas_asociacion.html#say_hello',
                                                                            'nbdev_test/asociacion.py')},
            'nbdev_test.core': {'nbdev_test.core.foo': ('core.html#foo', 'nbdev_test/core.py')}}}
