# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_intro_reglas_asociacion.ipynb.

# %% auto 0
__all__ = ['say_hello']

# %% ../nbs/00_intro_reglas_asociacion.ipynb 10
def say_hello(to):
    "Say hello to somebody"
    return f'Hello {to}!'
